services:
  postgres:
    container_name: springboot_template
    image: postgres
    ports: ["5432:5432"]
    env_file:
      - .env
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${databasePassword}
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
    name: springboot_template
